# Variance Reduction for Asian Options
In this notebook, we reduce variance of Monte Carlo pricing of Asian options via anthithetic sampling and control variates. For simplicity, we will only deal with call options. The implementation for put options is very similar.

Remember that whereas the payoff of European options solely depends on the price of the underlying stock at the time of maturity, the payoff of Asian options depends on the price of the underlying asset at a predetermined discrete set of times between options' inception and maturity. This fixed set of dates is called monitoring dates. We consider only two types of Asian options in this notebook: those whose payoff is determined by the geometric mean of the price of the underlying asset at monitoring dates and those by the arithmetic mean. The former has a closed form analytic solution, whereas the latter does not (we will have to rely on Monte Carlo estimation as a result).

We assume that the stock prices follow Geometric Brownian Motion, i.e. the price $S_t$ at time $t$ of a stock can be expressed as
$$
S_t = S_0 \exp \left\{ \left( r - \frac{1}{2} \sigma^2 \right) t + \sigma W_t \right\}
$$
where $S_0$ is the initial stock price (at time 0), $r$ is the risk-free interest rate, $\sigma$ is the volatility of the stock, and $W_t$ is the standard Brownian motion.

In [1]:
import numpy as np
import pandas as pd
from scipy.stats import norm
from scipy.stats.mstats import gmean
import time

print('numpy version: ',np.__version__)
print('pandas version: ',pd.__version__)

numpy version:  1.18.1
pandas version:  0.25.3

### Geometric Asian Options

A geometric Asian call option with strike price $K$ is a path-dependent option whose payoff at maturity $T$ is $(\bar{S}_G - K)^+$, where $\bar{S}_G$ is the geometric mean of the stock prices for a given set of monitoring dates $0 \leq t_1 < t_2 < \cdots < t_m \leq T$. The geometric mean of stock prices denoted by $\bar{S}_G$ is defined by
$$
\bar{S}_G = \left( \prod_{i=1}^{m} S_{t_i} \right) ^ {1 /m}
$$
It is fairly straighforward to see that $\log (\bar{S}_G) \sim N(\bar{\mu}, \bar{\sigma}^2)$, where
$$
\bar{\mu} = \log S_0 + \left(r - \frac{1}{2} \sigma^2 \right) \bar{t}, \quad \text{where} \quad \bar{t} = \frac{1}{m} \sum_{i=1}^m t_i
$$
$$
\bar{\sigma}^2 = \frac{\sigma^2}{m^2} \sum_{i=1}^m (2m - 2i + 1) t_i
$$
Therefore, the price of this option has the closed form analytic solution:
$$
\mathbb{E}[(\bar{S}_G - K)^+] = e^{-rT} \left( e^{\bar{\mu} + \frac{1}{2} \bar{\sigma}^2} \Phi(\bar{\sigma} - \theta) - K \Phi(-\theta) \right) \quad
\text{with} \quad \theta = \frac{1}{\bar{\sigma}} \left(\log K - \bar{\mu} \right)
$$
and $\Phi$ is the $CDF$ of standard normal.

#### The Black-Scholes Calculation of Geometric Asian Call Option

In [2]:
# For simplicity we assume that the monitoring dates are at the end of each month

def BS_asian_geometric_call(S_0, r, sigma, K, T):
    '''
    Black-Scholes price for a geometric Asian call option:
    S_0 - price of the underlying stock at time 0
    r - annual risk-free interest rate in decimal
    sigma - volatility of the underlying stock
    K - strike price
    T - time to maturity in years
    The result is rounded to 5 decimal places
    '''
    t = np.floor(12 * T)
    t_bar = (t + 1) / 24
    mu_bar = np.log(S_0) + (r - 0.5 * sigma ** 2) * t_bar
    sigma_bar = np.sqrt(((sigma ** 2) / (t ** 2)) * 1 / 72 * t * (t + 1) * (2 * t + 1))
    theta = (1 / sigma_bar) * (np.log(K) - mu_bar)
    bs_asian_geometric_call_price = np.exp(-r * T) * (np.exp(mu_bar + 0.5 * sigma_bar ** 2) * norm.cdf(sigma_bar - theta) - K * norm.cdf(-theta))
    return round(bs_asian_geometric_call_price, 5)

#### Plain Monte Carlo Estimation of Geometric Asian Call Option

In [3]:
# For simplicity we assume that the monitoring dates are at the end of each month

def MC_asian_geometric_call(S_0, r, sigma, K, T, n):
    '''
    Price estimate for geometric Asian call option using Monte Carlo simulation:
    We will generate paths for the Geometric Brownian Motion
    S_0 - price of the underlying stock at time 0
    r - annual risk-free interest rate in decimal
    sigma - volatility of the underlying stock
    K - strike price
    T - time to maturity in years
    n - number of iterations
    Returns both the price and standard error
    The results are  rounded to 5 decimal places
    '''
    t = np.floor(12 * T)
    Z = (r - 0.5 * sigma **2) * (1/12) + sigma * (1 / np.sqrt(12)) * np.random.standard_normal(size=(n, int(t)))
    W = np.cumsum(Z, axis=1) 
    Y = S_0 * np.exp(W)
    X1 = gmean(Y, axis=1)
    X = np.exp(-r * T) * np.maximum(X1 - K, np.zeros(n))   
    asian_geometric_call_price = np.mean(X)
    asian_geometric_call_se = np.std(X) / np.sqrt(n)
    return round(asian_geometric_call_price, 5), round(asian_geometric_call_se, 5)

#### Monte Carlo with Antithetic Sampling Estimation of Geometric Asian Call Option

In [4]:
# For simplicity we assume that the monitoring dates are at the end of each month

def MC_asian_geometric_call_as(S_0, r, sigma, K, T, n):
    '''
    Price estimate for geometric Asian call option using Monte Carlo simulation
    with antithetic sampling:
    We will generate paths for the Geometric Brownian Motion
    S_0 - price of the underlying stock at time 0
    r - annual risk-free interest rate in decimal
    sigma - volatility of the underlying stock
    K - strike price
    T - time to maturity in years
    n - total number of samples (n/2 generated) and (n/2 by antithetic sampling)
    Returns both the price and standard error
    The results are  rounded to 5 decimal places
    '''
    t = np.floor(12 * T)
    U0 = np.random.standard_normal(size=(int(n/2), int(t)))
    U = np.concatenate((U0, -U0), axis=0)
    Z = (r - 0.5 * sigma **2) * (1/12) + sigma * (1 / np.sqrt(12)) * U
    W = np.cumsum(Z, axis=1) 
    Y = S_0 * np.exp(W)
    X1 = gmean(Y, axis=1)
    X = np.exp(-r * T) * np.maximum(X1 - K, np.zeros(n))   
    asian_geometric_call_price = np.mean(X)
    asian_geometric_call_se = np.std(X) / np.sqrt(n)
    return round(asian_geometric_call_price, 5), round(asian_geometric_call_se, 5)

#### Comparison of the Analytic Price and the Monte Carlo Estimates

We will now compare the analytic price of call options and their Monte Carlo estimates (both plain and with antithetic sampling) for various strike prices and various sample sizes.

#### Geometric Asian Call Option with strike price $K=40$,  $S_0 = 50$, $r=0.05$, $\sigma=0.2$, and $T=1$.

In [5]:
np.random.seed(2020)
sample_size = [1e4, 1e5, 1e6, 1e7]
mc_estimates = []
mc_se = []
bs_price = np.repeat(BS_asian_geometric_call(50, 0.05, 0.2, 40, 1), 4)
mc_time = []

for n in sample_size:
    time0 = time.time()
    mc_call = MC_asian_geometric_call(50, 0.05, 0.2, 40, 1, int(n))
    time1 = time.time()
    mc_estimates.append(mc_call[0])
    mc_se.append(mc_call[1])
    mc_time.append(time1 - time0)

df = pd.DataFrame({'Sample Size': sample_size, 'Black-Scholes Price': bs_price, 
                   'Plain MC Estimate': mc_estimates, 'Plain MC se': mc_se, 'Plain MC time in s': mc_time})
df

,Sample Size,Black-Scholes Price,Plain MC Estimate,Plain MC se,Plain MC time in s
0,10000.0,10.69977,10.76211,0.05897,0.006971
1,100000.0,10.69977,10.71504,0.01872,0.068464
2,1000000.0,10.69977,10.70176,0.00591,0.723668
3,10000000.0,10.69977,10.70076,0.00187,7.246052

In [6]:
np.random.seed(2020)
sample_size = [1e4, 1e5, 1e6, 1e7]
mc_estimates = []
mc_se = []
bs_price = np.repeat(BS_asian_geometric_call(50, 0.05, 0.2, 40, 1), 4)
mc_time = []

for n in sample_size:
    time0 = time.time()
    mc_call = MC_asian_geometric_call_as(50, 0.05, 0.2, 40, 1, int(n))
    time1 = time.time()
    mc_estimates.append(mc_call[0])
    mc_se.append(mc_call[1])
    mc_time.append(time1 - time0)

df = pd.DataFrame({'Sample Size': sample_size, 'Black-Scholes Price': bs_price, 
                   'MC w/ AS Estimate': mc_estimates, 'MC w/ AS se': mc_se, 'MC w/AS time in s': mc_time})
df

,Sample Size,Black-Scholes Price,MC w/ AS Estimate,MC w/ AS se,MC w/AS time in s
0,10000.0,10.69977,10.71688,0.05996,0.005952
1,100000.0,10.69977,10.69871,0.01865,0.066463
2,1000000.0,10.69977,10.69969,0.00591,0.599208
3,10000000.0,10.69977,10.69992,0.00187,6.988593

#### Geometric Asian Call Option with strike price $K=60$,  $S_0 = 50$, $r=0.05$, $\sigma=0.2$, and $T=1$.

In [7]:
np.random.seed(2020)
sample_size = [1e4, 1e5, 1e6, 1e7]
mc_estimates = []
mc_se = []
bs_price = np.repeat(BS_asian_geometric_call(50, 0.05, 0.2, 60, 1), 4)
mc_time = []

for n in sample_size:
    time0 = time.time()
    mc_call = MC_asian_geometric_call(50, 0.05, 0.2, 60, 1, int(n))
    time1 = time.time()
    mc_estimates.append(mc_call[0])
    mc_se.append(mc_call[1])
    mc_time.append(time1 - time0)

df = pd.DataFrame({'Sample Size': sample_size, 'Black-Scholes Price': bs_price, 
                   'Plain MC Estimate': mc_estimates, 'Plain MC se': mc_se, 'Plain MC time in s': mc_time})
df

,Sample Size,Black-Scholes Price,Plain MC Estimate,Plain MC se,Plain MC time in s
0,10000.0,0.29875,0.30135,0.01310,0.010417
1,100000.0,0.29875,0.30430,0.00427,0.072417
2,1000000.0,0.29875,0.29880,0.00133,0.673070
3,10000000.0,0.29875,0.29845,0.00042,7.162599

In [8]:
np.random.seed(2020)
sample_size = [1e4, 1e5, 1e6, 1e7]
mc_estimates = []
mc_se = []
bs_price = np.repeat(BS_asian_geometric_call(50, 0.05, 0.2, 60, 1), 4)
mc_time = []

for n in sample_size:
    time0 = time.time()
    mc_call = MC_asian_geometric_call_as(50, 0.05, 0.2, 60, 1, int(n))
    time1 = time.time()
    mc_estimates.append(mc_call[0])
    mc_se.append(mc_call[1])
    mc_time.append(time1 - time0)

df = pd.DataFrame({'Sample Size': sample_size, 'Black-Scholes Price': bs_price, 
                   'MC w/ AS Estimate': mc_estimates, 'MC w/ AS se': mc_se, 'MC w/AS time in s': mc_time})
df

,Sample Size,Black-Scholes Price,MC w/ AS Estimate,MC w/ AS se,MC w/AS time in s
0,10000.0,0.29875,0.32060,0.01403,0.006002
1,100000.0,0.29875,0.29929,0.00421,0.066456
2,1000000.0,0.29875,0.29846,0.00133,0.618510
3,10000000.0,0.29875,0.29900,0.00042,6.352268

#### Observations:
* If one increases the sample size in a Monte Carlo estimation by a factor of $n$, the standard error will be reduced by a factor of $\sqrt n$. One can easily observe this phenomennon by comparing the 1st and the 3rd rows (or 2nd and 4th for that matter) in each dataframe above by noting the 100-fold increase in sample size and 10-fold decrease in standard error.
* Anthitetic sampling did not reduce the standard error, but resulted in a slight reduction of computation times.

### Arithmetic Asian Options

An arithmetic Asian call option with strike price $K$ is a path-dependent option whose payoff at maturity $T$ is $(\bar{S}_A - K)^+$, where $\bar{S}_A$ is the arithmetic mean of the stock prices for a given set of monitoring dates $0 \leq t_1 < t_2 < \cdots < t_m \leq T$. The arithmetic mean of stock prices denoted by $\bar{S}_A$ is defined by:
$$
\bar{S}_A = \frac{1}{m} \left( \sum_{i=1}^{m} S_{t_i} \right)
$$
Unlike geometric Asian options, arithmetic Asian options do not have an analytic formula for pricing / valuation; therefore, we will have to estimate them. Again, we will use Monte Carlo for that purpose.

#### Plain Monte Carlo Estimation of Arithmetic Asian Options

In [9]:
# For simplicity we assume that the monitoring dates are at the end of each month

def MC_asian_arithmetic_call(S_0, r, sigma, K, T, n):
    '''
    Price estimate for arithmetic Asian call option using Monte Carlo simulation:
    We will generate paths for the Geometric Brownian Motion
    S_0 - price of the underlying stock at time 0
    r - annual risk-free interest rate in decimal
    sigma - volatility of the underlying stock
    K - strike price
    T - time to maturity in years
    n - number of iterations
    Returns both the price and standard error
    The results are  rounded to 5 decimal places
    '''
    t = np.floor(12 * T)
    Z = (r - 0.5 * sigma **2) * (1/12) + sigma * (1 / np.sqrt(12)) * np.random.standard_normal(size=(n, int(t)))
    W = np.cumsum(Z, axis=1) 
    Y = S_0 * np.exp(W)
    X1 = np.mean(Y, axis=1)
    X = np.exp(-r * T) * np.maximum(X1 - K, np.zeros(n))   
    asian_arithmetic_call_price = np.mean(X)
    asian_arithmetic_call_se = np.std(X) / np.sqrt(n)
    return round(asian_arithmetic_call_price, 5), round(asian_arithmetic_call_se, 5)

#### Monte Carlo with Antithetic Sampling Estimation of Arithmetic Asian Options

In [10]:
# For simplicity we assume that the monitoring dates are at the end of each month

def MC_asian_arithmetic_call_as(S_0, r, sigma, K, T, n):
    '''
    Price estimate for arithmetic Asian call option using Monte Carlo simulation
    with antithetic sampling:
    We will generate paths for the Geometric Brownian Motion
    S_0 - price of the underlying stock at time 0
    r - annual risk-free interest rate in decimal
    sigma - volatility of the underlying stock
    K - strike price
    T - time to maturity in years
    n - total number of samples (n/2 generated) and (n/2 by antithetic sampling)
    Returns both the price and standard error
    The results are  rounded to 5 decimal places
    '''
    t = np.floor(12 * T)
    U0 = np.random.standard_normal(size=(int(n/2), int(t)))
    U = np.concatenate((U0, -U0), axis=0)
    Z = (r - 0.5 * sigma **2) * (1/12) + sigma * (1 / np.sqrt(12)) * U
    W = np.cumsum(Z, axis=1) 
    Y = S_0 * np.exp(W)
    X1 = np.mean(Y, axis=1)
    X = np.exp(-r * T) * np.maximum(X1 - K, np.zeros(n))   
    asian_arithmetic_call_price = np.mean(X)
    asian_arithmetic_call_se = np.std(X) / np.sqrt(n)
    return round(asian_arithmetic_call_price, 5), round(asian_arithmetic_call_se, 5)

#### Monte Carlo Estimation with Control Variates
We will estimate the price of an arithmetic Asian call option using Monte Carlo with the price of geometric Asian call option serving as the control variate.

In [11]:
# For simplicity we assume that the monitoring dates are at the end of each month

def MC_asian_arithmetic_call_cv(S_0, r, sigma, K, T, n):
    '''
    Price estimate for arithmetic Asian call option using Monte Carlo simulation
    with the price of geometric Asian option as control variate:
    We will generate paths for the Geometric Brownian Motion
    S_0 - price of the underlying stock at time 0
    r - annual risk-free interest rate in decimal
    sigma - volatility of the underlying stock
    K - strike price
    T - time to maturity in years
    n - number of iterations
    Returns both the price and standard error
    The results are  rounded to 5 decimal places
    '''
    t = np.floor(12 * T)
    Z = (r - 0.5 * sigma **2) * (1/12) + sigma * (1 / np.sqrt(12)) * np.random.standard_normal(size=(n, int(t)))
    #estimation of b_star using 1000 samples
    p = BS_asian_geometric_call(S_0, r, sigma, K, T)
    z = (r - 0.5 * sigma **2) * (1/12) + sigma * (1 / np.sqrt(12)) * np.random.standard_normal(size=(1000, int(t)))
    w = np.cumsum(z, axis=1)
    x = np.exp(-r * T) * np.maximum(np.mean(S_0 * np.exp(w), axis=1) - K, np.zeros(1000))
    y = np.exp(-r * T) * np.maximum(gmean(S_0 * np.exp(w), axis=1) - K, np.zeros(1000)) - p
    b_star = np.cov(x, y)[0, 1] / np.var(y)
    #back to MC
    W = np.cumsum(Z, axis=1) 
    X = np.exp(-r * T) * np.maximum(np.mean(S_0 * np.exp(W), axis=1) - K, np.zeros(n))
    Y = np.exp(-r * T) * np.maximum(gmean(S_0 * np.exp(W), axis=1) - K, np.zeros(n)) - p
    U = X - b_star * Y
    asian_arithmetic_call_price = np.mean(U)
    asian_arithmetic_call_se = np.std(U) / np.sqrt(n)
    return round(asian_arithmetic_call_price, 5), round(asian_arithmetic_call_se, 5)

#### Arithmetic Asian Call Option with strike price $K=40$,  $S_0 = 50$, $r=0.05$, $\sigma=0.2$, and $T=1$.

In [12]:
np.random.seed(2020)
sample_size = [1e4, 1e5, 1e6, 1e7]
mc_estimates = []
mc_se = []
bs_price = np.repeat(np.nan, 4)
mc_time = []

for n in sample_size:
    time0 = time.time()
    mc_call = MC_asian_arithmetic_call(50, 0.05, 0.2, 40, 1, int(n))
    time1 = time.time()
    mc_estimates.append(mc_call[0])
    mc_se.append(mc_call[1])
    mc_time.append(time1 - time0)

df = pd.DataFrame({'Sample Size': sample_size, 'Black-Scholes Price': bs_price, 
                   'Plain MC Estimate': mc_estimates, 'Plain MC se': mc_se, 'Plain MC time in s': mc_time})
df

,Sample Size,Black-Scholes Price,Plain MC Estimate,Plain MC se,Plain MC time in s
0,10000.0,NaN,10.91991,0.05976,0.007977
1,100000.0,NaN,10.87548,0.01897,0.064977
2,1000000.0,NaN,10.86173,0.00599,0.603631
3,10000000.0,NaN,10.86057,0.00189,6.073971

In [13]:
np.random.seed(2020)
sample_size = [1e4, 1e5, 1e6, 1e7]
mc_estimates = []
mc_se = []
bs_price = np.repeat(np.nan, 4)
mc_time = []

for n in sample_size:
    time0 = time.time()
    mc_call = MC_asian_arithmetic_call_as(50, 0.05, 0.2, 40, 1, int(n))
    time1 = time.time()
    mc_estimates.append(mc_call[0])
    mc_se.append(mc_call[1])
    mc_time.append(time1 - time0)

df = pd.DataFrame({'Sample Size': sample_size, 'Black-Scholes Price': bs_price, 
                   'MC w/ AS Estimate': mc_estimates, 'MC w/ AS se': mc_se, 'MC w/ AS time in s': mc_time})
df

,Sample Size,Black-Scholes Price,MC w/ AS Estimate,MC w/ AS se,MC w/ AS time in s
0,10000.0,NaN,10.87554,0.06079,0.005474
1,100000.0,NaN,10.85812,0.01889,0.055005
2,1000000.0,NaN,10.85946,0.00599,0.508937
3,10000000.0,NaN,10.85979,0.00189,5.219394

In [14]:
np.random.seed(2020)
sample_size = [1e4, 1e5, 1e6, 1e7]
mc_estimates = []
mc_se = []
bs_price = np.repeat(np.nan, 4)
mc_time = []

for n in sample_size:
    time0 = time.time()
    mc_call = MC_asian_arithmetic_call_cv(50, 0.05, 0.2, 40, 1, int(n))
    time1 = time.time()
    mc_estimates.append(mc_call[0])
    mc_se.append(mc_call[1])
    mc_time.append(time1 - time0)

df = pd.DataFrame({'Sample Size': sample_size, 'Black-Scholes Price': bs_price, 
                   'MC w/ CV Estimate': mc_estimates, 'MC w/ CV se': mc_se, 'MC w/ CV time in s': mc_time})
df

,Sample Size,Black-Scholes Price,MC w/ CV Estimate,MC w/ CV se,MC w/ CV time in s
0,10000.0,NaN,10.85683,0.00144,0.109118
1,100000.0,NaN,10.86009,0.00047,0.102177
2,1000000.0,NaN,10.85971,0.00015,0.905736
3,10000000.0,NaN,10.85957,0.00005,8.987009

#### Arithmetic Asian Call Option with strike price $K=60$,  $S_0 = 50$, $r=0.05$, $\sigma=0.2$, and $T=1$.

In [15]:
np.random.seed(2020)
sample_size = [1e4, 1e5, 1e6, 1e7]
mc_estimates = []
mc_se = []
bs_price = np.repeat(np.nan, 4)
mc_time = []

for n in sample_size:
    time0 = time.time()
    mc_call = MC_asian_arithmetic_call(50, 0.05, 0.2, 60, 1, int(n))
    time1 = time.time()
    mc_estimates.append(mc_call[0])
    mc_se.append(mc_call[1])
    mc_time.append(time1 - time0)

df = pd.DataFrame({'Sample Size': sample_size, 'Black-Scholes Price': bs_price, 
                   'Plain MC Estimate': mc_estimates, 'Plain MC se': mc_se, 'Plain MC time in s': mc_time})
df

,Sample Size,Black-Scholes Price,Plain MC Estimate,Plain MC se,Plain MC time in s
0,10000.0,NaN,0.34048,0.01434,0.005950
1,100000.0,NaN,0.34374,0.00466,0.064478
2,1000000.0,NaN,0.33741,0.00146,0.605657
3,10000000.0,NaN,0.33708,0.00046,6.183588

In [16]:
np.random.seed(2020)
sample_size = [1e4, 1e5, 1e6, 1e7]
mc_estimates = []
mc_se = []
bs_price = np.repeat(np.nan, 4)
mc_time = []

for n in sample_size:
    time0 = time.time()
    mc_call = MC_asian_arithmetic_call_as(50, 0.05, 0.2, 60, 1, int(n))
    time1 = time.time()
    mc_estimates.append(mc_call[0])
    mc_se.append(mc_call[1])
    mc_time.append(time1 - time0)

df = pd.DataFrame({'Sample Size': sample_size, 'Black-Scholes Price': bs_price, 
                   'MC w/ AS Estimate': mc_estimates, 'MC w/ AS se': mc_se, 'MC w/ AS time in s': mc_time})
df

,Sample Size,Black-Scholes Price,MC w/ AS Estimate,MC w/ AS se,MC w/ AS time in s
0,10000.0,NaN,0.36107,0.01536,0.005456
1,100000.0,NaN,0.33768,0.00460,0.053568
2,1000000.0,NaN,0.33700,0.00145,0.516378
3,10000000.0,NaN,0.33769,0.00046,5.329305

In [17]:
np.random.seed(2020)
sample_size = [1e4, 1e5, 1e6, 1e7]
mc_estimates = []
mc_se = []
bs_price = np.repeat(np.nan, 4)
mc_time = []

for n in sample_size:
    time0 = time.time()
    mc_call = MC_asian_arithmetic_call_cv(50, 0.05, 0.2, 60, 1, int(n))
    time1 = time.time()
    mc_estimates.append(mc_call[0])
    mc_se.append(mc_call[1])
    mc_time.append(time1 - time0)

df = pd.DataFrame({'Sample Size': sample_size, 'Black-Scholes Price': bs_price, 
                   'MC w/ CV Estimate': mc_estimates, 'MC w/ CV se': mc_se, 'MC w/ CV time in s': mc_time})
df

,Sample Size,Black-Scholes Price,MC w/ CV Estimate,MC w/ CV se,MC w/ CV time in s
0,10000.0,NaN,0.33766,0.00092,0.011879
1,100000.0,NaN,0.33764,0.00030,0.100193
2,1000000.0,NaN,0.33737,0.00010,0.908223
3,10000000.0,NaN,0.33741,0.00003,9.050996

#### Observations:
* Again the antithetic variable resulted in a reduction of computation time rather than reduction in variance.
* The variance reduction achieved by the control variate method is significant despite the increase in computation time. This reflects the strong correlation between the arithmetic mean and geometric mean.